### ISSUE TITLE
Request: more detailed information in the README

### ISSUE THREAD

**Issue by depau** [crondog/arch-flo#1]
I've been following your guide, and I think I did pretty much everything right as I get it to boot and I can prove that at some point the X.org server starts as I find a log in /var/log, but yet I don't get X.org running.
The refresher is compiled and it works, or at least, it doesn't give any error.
Anyway I have this X.org log, you can give it a look: http://paste.ubuntu.com/7093541/
I'm wondering though why is it trying to use the tegra driver when it has an adreno... I don't know.

Anyway good job, this project seems promising :)
If I get it to run at least X.org in an usable way I'll write a step-by-step guide on some website :) :+1: 

EDIT:
Even if it's not strictly related to the display server problem, I'm also attaching this kernel log. It's the one you provided in the post, I followed the link, built it and then wrapped it together into a bootimage with your initramfs. http://paste.ubuntu.com/7093547/

2nd EDIT:
How about using Wayland instead of X.org? As far as I know, wayland can use Android and MIR graphics drivers, which means that it would have access to OpenGL and stuff. I've never used wayland and I don't know exactly what desktop environments and programs are compatible with it, but it might be an idea.

**Comment by crondog** [comment]
I updated the readme https://github.com/crondog/arch-flo/commit/26eaa7becc566f382a29038369a7dc500ce18c86

This should contain the additional instructions to get it working

I am having issues with getting wayland working straight up. However wayland in X works

**Comment by depau** [comment]
OK thanks, I'll do the new steps and let you know.

**Comment by depau** [comment]
I followed all the steps. I built all the stuff for xorg, and it eventually starts (I can tell it because the logs don't show any error, because the screen turns black and because there's a Desktop directory in my home, obviously created by xfce's file manager (thunar?)). I don't see XFCE's hamster though.

Apparently the X server starts normally, but your refresher doesn't work. If I start the refresher as the same user as Xorg it can't open the framebuffer, and if I start it as root (using echo password | sudo -S refresher) it can open it, but in both cases I get "Failed FBIOPAN_DISPLAY".
I built the refresher using the compiler in the ubuntu package gcc-4.7-arm-linux-gnueabi, statically linked.

Another (easily solvable) problem is that both the PKGBUILDs don't have their LICENSE and COPYING files, and armv7h is not in the architectures array.

**Comment by depau** [comment]
Never mind, Xorg works! :) :+1:
I rebuilt the refresher using the tablet instead of cross compiling it.
I'll try the other stuff now....

**Comment by depau** [comment]
This is the stuff I'm still not getting to work:
- WiFi: I didn't quite understand the wpa_supplicant part. Where do I have to get the configuration file from?

USB On-The-Go doesn't work, SlimPort doesn't work (but it didn't expect it to :) ), and I have no idea on how to try NFC.

Kwin crashes, I suppose that's because it cannot use HW acceleration, Openbox works.

**Comment by crondog** [comment]
Do you mean the wpa_supplicant.conf? Just make it like the example one http://linux.die.net/man/5/wpa_supplicant.conf

USB-OTG should work. If you plug in your otg cable and run lsusb it should detect it. I can mount usb sticks

No idea about slimport as i dont have anything to test it with

And for now hw accel is borked

**Comment by depau** [comment]
In the README you said

```
6: Create a wpa_supplicant-nl80211@wlan0.service with your wpa_supplicant.conf details
```

And you didn't provide any path or any template. As it's a .service file I guess it is to be put into /etc/systemd/system, but I don't think putting the contents of wpa_supplicant.conf in there would be a great idea.
What do I have to do then? Create a regular wpa_supplicant.conf with my network configuration and put something else in wpa_supplicant-nl80211@wlan0.service?
Can I just use network manager? I find it easier to use...

For the other stuff, I'll double check. I didn't run lsusb after plugging in my usb stick, I just assumed that it didn't work as the led didn't turn on... my bad...

SlimPort: I don't know how to check myself. I have a SlimPort cable that I use on Android, so if you want me to do some tests with my tablet I'm available. In any case, this is the cable I bought: http://www.ebay.com/itm/171202238669?ssPageName=STRK:MEWNX:IT&_trksid=p3984.m1439.l2649
It is the original one from SlimPort, and it seems good enough. Sometimes I lose signal when moving the device, but if you want to get it for testing it's good. It should be the cheapest, as usually they cost around $40.

NFC: I have another NFC device, I'm sure Arch has documentation for that, I'll start trying...

**Comment by crondog** [comment]
Ok I uploaded my wpa service file. 

You can use network manager its up to you. But you need to make sure that the firmware.service file is loaded before trying to access the network (like in my service file) This should be done in the initramfs but i haven't gotten to doing that yet.

As for nfc, i have not come across anything which works with the bcm2079x. Intel might be supporting it with the neard project in the future

**Comment by willcast** [comment]
You might try mounting /data, manually adding an android_wifi group with matching GID, and symlinking in the Android config from /data/misc/wifi/wpa_supplicant.conf.

**Comment by crondog** [comment]
So this should all now work without hacking services/wpa etc. The service files do not depend on the firmware.service anymore so there should be less issues.

**Comment by willcast** [comment]
Well, the advantage would be that you automatically get the same wifi networks in both OSes. Saves time as long as nobody tries to install it as the only OS.

Also, I have a rom_info.txt that can make this bootable from https://github.com/Tasssadar/multirom (if anyone is interested)

**Comment by crondog** [comment]
Ah true. 

Is your rom_info.txt on your github? If so could I add a link to it for those interested ?

**Comment by willcast** [comment]
I'm about to put it on. Still writing the instructions into the README and right now my initcpio hooks, like yours, only support loop-mounted images (MultiROM also can have the root stored under a folder on the same FS).

**Comment by depau** [comment]
@willcast are you planning on making a MultiROM ROM with arch Linux? That'd be awesome! I actually stopped working on arch in my tablet because I have the 16gb version and I'm running out of space... I had to put arch on the shelf in order to free some space...

**Comment by willcast** [comment]
I might. I'd want to compile wayland support into mesa first so the users can have GNOME-3. I'll get around to it.

**Comment by depau** [comment]
That would be nice. Even if I don't use gnome, I find it the most suitable de for touch screens. The most suitable is unity I think, because of the global ui scale, but sadly it doesn't have Wayland support.

**Comment by willcast** [comment]
It's still going to use xorg. The problem is that the included mesa PKGBUILD doesn't have the wayland state tracker enabled. I don't want to rebuild gnome every time. 

I'm working on getting this on HP touchpad and Verizon Galaxy S3

**Comment by depau** [comment]
Good enough. Do you know if the hardware acceleration will work with xorg? Last time I tried gnome on flo it crashed.

**Comment by willcast** [comment]
Haven't tried it yet, but glxgears and projectM (under VLC) both work at full speed and stably.

Then again, I haven't been able to get GNOME shell to work on the TouchPad since Mesa support was first added to freedreno. It wasn't mesa, pcsx-rearmed and openarena both worked .

We always have Enlightenment if that breaks.

**Comment by depau** [comment]
Oh yeah, I really like enlightenment too, I forgot to mention it before... It works great on touch screens. The last time I tried to build it there was some building error in one of the core components.
I actually have never had the chance to try it, but I really like the fact that the devs are trying to put the touchscreen essential features.
I think I'll try some bodhi Linux live on my laptop at some point...

**Comment by willcast** [comment]
@crondog, did my pull request never come in? Is something wrong with it?

**Comment by crondog** [comment]
@willcast I did get your pull request. I just have not had the time to test the changes. I should be able to try it out before the end of this week.

**Comment by depau** [comment]
Any updates from this project?

**Comment by willcast** [comment]
Unfortunately not. My flo was stolen out of a hotel room.

**Comment by depau** [comment]
Sorry to hear that... @willcast

On July 28, 2014 7:59:58 AM CEST, Will Castro notifications@github.com wrote:

> Unfortunately not. My flo was stolen out of a hotel room.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/crondog/arch-flo/issues/1#issuecomment-50302748

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by depau** [comment]
I think this issue can be closed as the main problem has been solved after our improvements to the readme.
